=== pol51/OpenDiameter/cplusplus/libdiametereap/config/eap-tls.configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>

<xs:simpleType name="booleanType">
	<xs:restriction base="xs:string">
		<xs:pattern value="true|false"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="encryptionType">
	<xs:all>
		<xs:element name="pass_phrase" type="xs:string"/>
		<xs:element name="key_file" type="xs:string"/>
		<xs:element name="cert_file" type="xs:string"/>
		<xs:element name="random" type="xs:string"/>
		<xs:element name="ca_path" type="xs:string"/>
		<xs:element name="ca_cert" type="xs:string"/>
		<xs:element name="dh" type="xs:string"/>
		<xs:element name="rsa_key" type="xs:integer"/>
		<xs:element name="dh_key" type="xs:integer"/>
		<xs:element name="rsa_key_length" type="xs:integer"/>
		<xs:element name="dh_key_length" type="xs:integer"/>
		<xs:element name="verify_depth" type="xs:integer"/>
		<xs:element name="file_type" type="xs:integer" minOccurs="0" maxOccurs="1"/>
	</xs:all>
</xs:complexType>

<xs:complexType name="fragmentationType">
	<xs:all>
		<xs:element name="include_length" type="booleanType"/>
		<xs:element name="fragment_size" type="xs:integer"/>
	</xs:all>
</xs:complexType>

<xs:complexType name="serverType">
	<xs:sequence>
		<xs:element name="id_context" type="xs:integer"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="configuration_server">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="encryption" type="encryptionType"/>
			<xs:element name="fragmentation" type="fragmentationType"/>
			<xs:element name="server" type="serverType"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="configuration_client">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="encryption" type="encryptionType"/>
			<xs:element name="fragmentation" type="fragmentationType"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== pol51/OpenDiameter/cplusplus/libeap/config/client.eap-tls.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Configuration file for client always starts with "configuration_client" element as root -->
<configuration_client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation='eap-tls.configuration.xsd'>
	<!-- Encryption section. This section has a fixed list of elements.
		This information is needed for OpenSSL to work -->
	<encryption>
		<!-- Pass phrase for client cryptographic files -->
		<pass_phrase>cliente</pass_phrase>
		<!-- Key file -->
		<key_file>./tests/tls_config/peer/clt-key.pem</key_file>
		<!-- Certificate file -->
		<cert_file>./tests/tls_config/peer/clt-cert.pem</cert_file>
		<!-- File used to build ramdom numbers -->
		<random>./tests/tls_config/auth/random</random>
		<!-- Path for Certification Authorities -->
		<ca_path>./tests/tls_config/peer</ca_path>
		<!-- Certification Authority's certificate for Certification Authority that signs client certificate -->
		<ca_cert>./tests/tls_config/peer/ca-cert.pem</ca_cert>
		<!-- File implementation for Diffie-Hellman algorithm -->
		<dh>./tests/tls_config/auth/dh</dh>
		<!-- RSA Key -->
		<rsa_key>0</rsa_key>
		<!-- Diffie-Hellman Key -->
		<dh_key>1</dh_key>
		<!-- RSA key length -->
		<rsa_key_length>512</rsa_key_length>
		<!-- Diffie-Hellman key lenght -->
		<dh_key_length>512</dh_key_length>
		<!-- Maximum depth for the certificate chain verification that shall be allowed -->
		<verify_depth>1</verify_depth>
		<!-- Type of certificates:
			0: ASN1
			1: PEM
		-->
		<file_type>1</file_type>
	</encryption>
	<!-- Fragmentation section. This section has a fixed list of elements.
		This information is needed in packet fragmentation -->
	<fragmentation>
		<!-- Initial value for lenght flag in fragmentation -->
		<include_length>false</include_length>
		<!-- Fragment size -->
		<fragment_size>600</fragment_size>
	</fragmentation>
</configuration_client>

=== pol51/OpenDiameter/cplusplus/libeap/config/server.eap-tls.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Configuration file for server always starts with "configuration_server" element as root -->
<configuration_server xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation='eap-tls.configuration.xsd'>
	<!-- Encryption section. This section has a fixed list of elements.
		This information is needed for OpenSSL to work -->
	<encryption>
		<!-- Pass phrase for server cryptographic files -->
		<pass_phrase>servidor</pass_phrase>
		<!-- Key file -->
		<key_file>./tests/tls_config/auth/srv-key.pem</key_file>
		<!-- Certificate file -->
		<cert_file>./tests/tls_config/auth/srv-cert.pem</cert_file>
		<!-- File used to build ramdom numbers -->
		<random>./tests/tls_config/auth/random</random>
		<!-- Path for Certification Authorities -->
		<ca_path>./tests/tls_config/auth</ca_path>
		<!-- Certification Authority's certificate for Certification Authority that signs server certificate -->
		<ca_cert>./tests/tls_config/auth/ca-cert.pem</ca_cert>
		<!-- File implementation for Diffie-Hellman algorithm -->
		<dh>./tests/tls_config/auth/dh</dh>
		<!-- RSA Key -->
		<rsa_key>0</rsa_key>
		<!-- Diffie-Hellman Key -->
		<dh_key>1</dh_key>
		<!-- RSA key length -->
		<rsa_key_length>512</rsa_key_length>
		<!-- Diffie-Hellman key lenght -->
		<dh_key_length>512</dh_key_length>
		<!-- Maximum depth for the certificate chain verification that shall be allowed -->
		<verify_depth>1</verify_depth>
		<!-- Type of certificates:
			0: ASN1
			1: PEM
		-->
		<file_type>1</file_type>
	</encryption>
	<!-- Fragmentation section. This section has a fixed list of elements.
		This information is needed in packet fragmentation -->
	<fragmentation>
		<!-- Initial value for lenght flag in fragmentation -->
		<include_length>false</include_length>
		<!-- Fragment size -->
		<fragment_size>500</fragment_size>
	</fragmentation>
	<!-- Server specific section. This section has a fixed list of elements.
		This information is needed in packet fragmentation -->
	<server>
		<!-- Context identifier for server's OpenSSL initialization -->
		<id_context>100</id_context>
	</server>
</configuration_server>

=== pol51/OpenDiameter/cplusplus/applications/aaa/config/server.eap-fast.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Configuration file for server always starts with "configuration_server" element as root -->
<configuration_server xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation='eap-tls.configuration.xsd'>
	<!-- Encryption section. This section has a fixed list of elements.
		This information is needed for OpenSSL to work -->
	<encryption>
		<!-- Pass phrase for server cryptographic files -->
		<pass_phrase>srv-key</pass_phrase>
		<!-- Key file -->
		<key_file>/etc/opendiameter/aaa/config/fast/srv-key.pem</key_file>
		<!-- Certificate file -->
		<cert_file>/etc/opendiameter/aaa/config/fast/srv-cert.pem</cert_file>
		<!-- File used to build ramdom numbers -->
		<random>/etc/opendiameter/aaa/config/fast/random</random>
		<!-- Path for Certification Authorities -->
		<ca_path>/etc/opendiameter/aaa/config/fast</ca_path>
		<!-- Certification Authority's certificate for Certification Authority that signs server certificate -->
		<ca_cert>/etc/opendiameter/aaa/config/fast/ca-cert.pem</ca_cert>
		<pac_opaque_encr>000102030405060708090a0b0c0d0e0f</pac_opaque_encr>
		<!-- File implementation for Diffie-Hellman algorithm -->
		
		<dh>/etc/opendiameter/aaa/config/fast/dh</dh>
		<!-- RSA Key -->
		<rsa_key>0</rsa_key>
		<!-- Diffie-Hellman Key -->
		<dh_key>1</dh_key>
		<!-- RSA key length -->
		<rsa_key_length>512</rsa_key_length>
		<!-- Diffie-Hellman key lenght -->
		<dh_key_length>512</dh_key_length>
		<!-- Maximum depth for the certificate chain verification that shall be allowed -->
		<verify_depth>1</verify_depth>
		<!-- Type of certificates:
			0: ASN1
			1: PEM
		-->
		<file_type>1</file_type>
	</encryption>
	<!-- Fragmentation section. This section has a fixed list of elements.
		This information is needed in packet fragmentation -->
	<fragmentation>
		<!-- Initial value for lenght flag in fragmentation -->
		<include_length>false</include_length>
		<!-- Fragment size -->
		<fragment_size>500</fragment_size>
	</fragmentation>
	<!-- Server specific section. This section has a fixed list of elements.
		This information is needed in packet fragmentation -->
	<server>
		<!-- Context identifier for server's OpenSSL initialization -->
		<id_context>auth</id_context>
	</server>
</configuration_server>
