=== pol51/OpenDiameter/cplusplus/libdiametermip4/config/configuration.dtd
<?xml version="1.0" encoding="UTF-8" ?>

    <!ELEMENT configuration (general, parser, transport_mngt, session_mngt, log)>

     <!ELEMENT general (product, version, vendor_id, supported_vendor_id*,
                                      auth_application_id+, acct_application_id+,
                                      vendor_specific_application_id*)>

     <!ELEMENT product (#PCDATA)>
     <!ELEMENT version (#PCDATA)>
     <!ELEMENT vendor_id (#PCDATA)>
     <!ELEMENT supported_vendor_id (#PCDATA)>
     <!ELEMENT auth_application_id (#PCDATA)>
     <!ELEMENT acct_application_id (#PCDATA)>

     <!ELEMENT vendor_specific_application_id (vendor_id,
                                               (auth_application_id|acct_application_id))>

     <!ELEMENT parser (dictionary)>

     <!ELEMENT dictionary (#PCDATA)>

     <!ELEMENT transport_mngt (identity, realm, tcp_listen_port, sctp_listen_port, use_ipv6,
                               port, watchdog_timeout, reconnect_interval, reconnect_max,
                               request_retransmission_interval, max_request_retransmission_count,
                               advertised_hostname*, peer_table, route_table)>

     <!ELEMENT identity (#PCDATA)>
     <!ELEMENT realm (#PCDATA)>
     <!ELEMENT tcp_listen_port (#PCDATA)>
     <!ELEMENT sctp_listen_port (#PCDATA)>
     <!ELEMENT use_ipv6 (#PCDATA)>
     <!ELEMENT watchdog_timeout (#PCDATA)>
     <!ELEMENT reconnect_interval (#PCDATA)>
     <!ELEMENT reconnect_max (#PCDATA)>
     <!ELEMENT request_retransmission_interval (#PCDATA)>
     <!ELEMENT max_request_retransmission_count (#PCDATA)>
     <!ELEMENT advertised_hostname (#PCDATA)>

     <!ELEMENT peer_table (expiration_time,  peer+)>

     <!ELEMENT expiration_time (#PCDATA)>

     <!ELEMENT peer (hostname,  port,  use_sctp, tls_enabled)>

     <!ELEMENT hostname (#PCDATA)>
     <!ELEMENT port (#PCDATA)>
     <!ELEMENT use_sctp (#PCDATA)>
     <!ELEMENT tls_enabled (#PCDATA)>

     <!ELEMENT route_table (expire_time, route*, default_route)>

     <!ELEMENT expire_time (#PCDATA)>

     <!ELEMENT route (realm,  role, application+)>
     <!ELEMENT default_route (realm,  role, application+)>

     <!ELEMENT realm (#PCDATA)>
     <!ELEMENT role (#PCDATA)>

     <!ELEMENT application (application_id, vendor_id, peer_entry+)>

     <!ELEMENT application_id (#PCDATA)>
     <!ELEMENT vendor_id (#PCDATA)>

     <!ELEMENT peer_entry (server, metric)>

     <!ELEMENT server (#PCDATA)>
     <!ELEMENT metric (#PCDATA)>

     <!ELEMENT session_mngt (max_sessions, auth_sessions, acct_sessions)>

     <!ELEMENT max_sessions (#PCDATA)>

     <!ELEMENT auth_sessions (stateful, session_timeout, lifetime_timeout,
                                     grace_period_timeout, abort_retry_timeout)>

     <!ELEMENT stateful (#PCDATA)>
     <!ELEMENT session_timeout (#PCDATA)>
     <!ELEMENT lifetime_timeout (#PCDATA)>
     <!ELEMENT grace_period_timeout (#PCDATA)>
     <!ELEMENT abort_retry_timeout (#PCDATA)>

     <!ELEMENT acct_sessions (session_timeout, interim_interval,
                                    realtime)>

     <!ELEMENT interim_interval (#PCDATA)>
     <!ELEMENT realtime (#PCDATA)>

     <!ELEMENT log (flags, target)>

     <!ELEMENT flags (debug, trace, info)>

     <!ELEMENT debug (#PCDATA)>
     <!ELEMENT trace (#PCDATA)>
     <!ELEMENT info (#PCDATA)>

     <!ELEMENT target (console, syslog)>

     <!ELEMENT console (#PCDATA)>
     <!ELEMENT syslog (#PCDATA)>

=== pol51/OpenDiameter/cplusplus/libdiametermip4/config/hac.local.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<configuration>

<!-- check attributes: vendor_id acc_appl_id role metric , MT sep. 15 2004 -->

   <general>
      <product>Open Diameter</product>
      <version>1</version>
      <vendor_id>0</vendor_id>
      <supported_vendor_id>0</supported_vendor_id>
      <supported_vendor_id>1</supported_vendor_id>
      <auth_application_id>1</auth_application_id>
      <auth_application_id>2</auth_application_id>
      <acct_application_id>3</acct_application_id>
      <acct_application_id>4</acct_application_id>
      <vendor_specific_application_id>
          <vendor_id>31</vendor_id>
          <auth_application_id>2</auth_application_id>
      </vendor_specific_application_id>
      <vendor_specific_application_id>
          <vendor_id>41</vendor_id>
          <acct_application_id>6</acct_application_id>
      </vendor_specific_application_id>
   </general>
   <parser> 
      <dictionary>config/dictionary.xml</dictionary>
   </parser>
   <transport_mngt>
      <identity>hac.homedomain.com</identity>
      <realm>homedomain.com</realm>
      <tcp_listen_port>1800</tcp_listen_port>
      <sctp_listen_port>1801</sctp_listen_port>
      <use_ipv6>0</use_ipv6>
      <watchdog_timeout>3</watchdog_timeout>
      <reconnect_interval>30</reconnect_interval>
      <reconnect_max>3</reconnect_max>
      <request_retransmission_interval>10</request_retransmission_interval>
      <max_request_retransmission_count>3</max_request_retransmission_count>
      <advertised_hostname>hac01.homedomain.com</advertised_hostname>
      <advertised_hostname>hac02.homedomain.com</advertised_hostname>
      <peer_table>
          <expiration_time>1</expiration_time>
          <peer>
              <hostname>aaaserver.homedomain.com</hostname>
              <port>1802</port>
              <use_sctp>0</use_sctp>
              <tls_enabled>0</tls_enabled>
          </peer>
      </peer_table>
      <route_table>
          <expire_time>360</expire_time>
          <route>
             <realm>homedomain.com</realm>
             <role>1</role>
             <redirect_usage>0</redirect_usage>
             <application>
                <application_id>3</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>aaaserver.homedomain.com</server>
                    <metric>2</metric>
                </peer_entry>
             </application> 
             <application>
                <application_id>2</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>aaaserver.homedomain.com</server>
                    <metric>2</metric>
                </peer_entry>
             </application>
          </route>
     </route_table>
   </transport_mngt>
   <session_mngt>
      <max_sessions>10000</max_sessions>
      <auth_sessions>
         <stateful>1</stateful>
         <session_timeout>361</session_timeout>
         <lifetime_timeout>360</lifetime_timeout>
         <grace_period_timeout>30</grace_period_timeout>
         <abort_retry_timeout>20</abort_retry_timeout>
      </auth_sessions>
      <acct_sessions>
         <session_timeout>30</session_timeout>
         <interim_interval>5</interim_interval>
         <realtime>1</realtime>
      </acct_sessions>
   </session_mngt>
   <log>
      <flags>
         <debug>enabled</debug>
         <trace>enabled</trace>
         <info>enabled</info>
      </flags>
      <target>
         <console>enabled</console>
         <syslog>disabled</syslog>
      </target>
   </log>
</configuration>

=== pol51/OpenDiameter/cplusplus/libdiametermip4/config/server.local.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<configuration>
   <general>
      <product>Open Diameter</product>
      <version>1</version>
      <vendor_id>0</vendor_id>
      <supported_vendor_id>0</supported_vendor_id>
      <supported_vendor_id>1</supported_vendor_id>
      <auth_application_id>1</auth_application_id>
      <auth_application_id>2</auth_application_id>
      <acct_application_id>3</acct_application_id>
      <acct_application_id>4</acct_application_id>
      <vendor_specific_application_id>
          <vendor_id>31</vendor_id>
          <auth_application_id>2</auth_application_id>
      </vendor_specific_application_id>
      <vendor_specific_application_id>
          <vendor_id>41</vendor_id>
          <acct_application_id>6</acct_application_id>
      </vendor_specific_application_id>
   </general>
   <parser> 
      <dictionary>config/dictionary.xml</dictionary>
   </parser>
   <transport_mngt>
      <identity>aaaserver.telcordias.com</identity>
      <realm>telcordias.com</realm>
      <tcp_listen_port>1802</tcp_listen_port>
      <sctp_listen_port>1803</sctp_listen_port>
      <use_ipv6>0</use_ipv6>
      <watchdog_timeout>4</watchdog_timeout>
      <reconnect_interval>30</reconnect_interval>
      <reconnect_max>3</reconnect_max>
      <request_retransmission_interval>10</request_retransmission_interval>
      <max_request_retransmission_count>3</max_request_retransmission_count>
      <advertised_hostname>aaaserver01.telcordias.com</advertised_hostname>
      <advertised_hostname>aaaserver02.telcordias.com</advertised_hostname>
      <peer_table>
          <expiration_time>1</expiration_time>
          <peer>
              <hostname>mhc.telcordia.com</hostname>
              <port>1801</port>
              <use_sctp>0</use_sctp>
              <tls_enabled>0</tls_enabled>
          </peer>
      </peer_table>
      <route_table>
          <expire_time>0</expire_time>
          <route>
             <realm>telcordia.com</realm>
             <role>0</role> 
             <redirect_usage>0</redirect_usage>
             <application>
                <application_id>3</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>mhc.telcordia.com</server>
                    <metric>2</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas2.research1.org</server>
                    <metric>4</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas3.research1.org</server>
                    <metric>5</metric>
                </peer_entry>
             </application>
             <application>
                <application_id>1</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>mhc.telcordia.com</server>
                    <metric>2</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas2.research1.org</server>
                    <metric>4</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas3.research1.org</server>
                    <metric>5</metric>
                </peer_entry>
             </application>
          </route>
          <default_route>
             <realm>telcordia.com</realm>
             <role>0</role> 
             <redirect_usage>0</redirect_usage>
             <application>
                <application_id>3</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>mhc.telcordia.com</server>
                    <metric>4</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas3.research1.org</server>
                    <metric>5</metric>
                </peer_entry>
             </application>
          </default_route>
      </route_table>
   </transport_mngt>
   <session_mngt>
      <max_sessions>10000</max_sessions>
      <stateful>1</stateful>
      <timers>
         <session>30</session>
         <lifetime>360</lifetime>
         <grace>30</grace>
         <abort_retry>20</abort_retry>
      </timers>
   </session_mngt>
   <log>
      <flags>
         <debug>enabled</debug>
         <trace>enabled</trace>
         <info>enabled</info>
      </flags>
      <target>
         <console>enabled</console>
         <syslog>enabled</syslog>
      </target>
   </log>
</configuration>

=== pol51/OpenDiameter/cplusplus/libdiameter/config/nas1.local.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<configuration>
   <general>
      <product>Open Diameter</product>
      <version>1</version>
      <vendor_id>0</vendor_id>
      <auth_application_id>-1</auth_application_id>
      <auth_application_id>5</auth_application_id>
      <auth_application_id>4</auth_application_id>
      <vendor_specific_application_id>
          <vendor_id>41</vendor_id>
          <auth_application_id>5</auth_application_id>
          <acct_application_id>6</acct_application_id>
      </vendor_specific_application_id>
   </general>
   <parser>
      <dictionary>config/dictionary.xml</dictionary>
   </parser>
   <transport_mngt>
      <identity>toshibapeer1.toshiba.com</identity>
      <realm>toshiba.com</realm>
      <tcp_listen_port>1812</tcp_listen_port>
      <sctp_listen_port>1813</sctp_listen_port>
      <use_ipv6>0</use_ipv6>
      <watchdog_timeout>4</watchdog_timeout>
      <reconnect_interval>30</reconnect_interval>
      <reconnect_max>3</reconnect_max>
      <request_retransmission_interval>10</request_retransmission_interval>
      <max_request_retransmission_count>3</max_request_retransmission_count>
      <advertised_hostname>toshibapeer1.toshiba.com</advertised_hostname>
      <peer_table>
          <expiration_time>1</expiration_time>
          <peer>
              <hostname>atospeer1.atos.com</hostname>
              <port>1812</port>
              <use_sctp>0</use_sctp>
              <tls_enabled>0</tls_enabled>
          </peer>
          <peer>
              <hostname>condorpeer2.condor.com</hostname>
              <port>1812</port>
              <use_sctp>0</use_sctp>
              <tls_enabled>0</tls_enabled>
          </peer>
      </peer_table>
      <route_table>
          <expire_time>0</expire_time>
          <route>
             <realm>condor.com</realm>
             <role>1</role> 
             <application>
                <application_id>4</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>condorpeer2.condor.com</server>
                    <metric>2</metric>
                </peer_entry>
             </application>
             <application>
                <application_id>5</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>condorpeer2.condor.com</server>
                    <metric>2</metric>
                </peer_entry>
             </application>
          </route>
          <default_route>
          <route>
             <realm>atos.com</realm>
             <role>1</role> 
             <application>
                <application_id>4</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>atospeer1.atos.com</server>
                    <metric>2</metric>
                </peer_entry>
             </application>
             <application>
                <application_id>5</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>atospeer1.condor.com</server>
                    <metric>2</metric>
                </peer_entry>
             </application>
          </route>
          <default_route>
             <realm>access1.net</realm>
             <role>0</role> 
             <application>
                <application_id>0</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>nas.access1.net</server>
                    <metric>4</metric>
                </peer_entry>
             </application>
          </default_route>
      </route_table>
   </transport_mngt>
   <session_mngt>
      <max_sessions>10000</max_sessions>
      <auth_sessions>
         <stateful>1</stateful>
         <session_timeout>30</session_timeout>
         <lifetime_timeout>360</lifetime_timeout>
         <grace_period_timeout>30</grace_period_timeout>
         <abort_retry_timeout>20</abort_retry_timeout>
      </auth_sessions>
      <acct_sessions>
         <session_timeout>30</session_timeout>
         <interim_interval>5</interim_interval>
         <realtime>1</realtime>
      </acct_sessions>
   </session_mngt>
   <log>
      <flags>
         <debug>enabled</debug>
         <trace>enabled</trace>
         <info>enabled</info>
      </flags>
      <target>
         <console>enabled</console>
         <syslog>enabled</syslog>
      </target>
   </log>
</configuration>

=== pol51/OpenDiameter/cplusplus/libdiameternasreq/config/client.local.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<configuration>
   <general>
      <product>Open Diameter</product>
      <version>1</version>
      <vendor_id>0</vendor_id>
      <supported_vendor_id>0</supported_vendor_id>
      <supported_vendor_id>1</supported_vendor_id>
      <auth_application_id>1</auth_application_id>
      <auth_application_id>2</auth_application_id>
      <auth_application_id>5</auth_application_id>
      <acct_application_id>3</acct_application_id>
      <acct_application_id>4</acct_application_id>
      <vendor_specific_application_id>
          <vendor_id>31</vendor_id>
          <auth_application_id>1</auth_application_id>
      </vendor_specific_application_id>
      <vendor_specific_application_id>
          <vendor_id>41</vendor_id>
          <acct_application_id>6</acct_application_id>
      </vendor_specific_application_id>
   </general>
   <parser> 
      <dictionary>config/dictionary.xml</dictionary>
   </parser>
   <transport_mngt>
      <identity>nas.research1.org</identity>
      <realm>research1.org</realm>
      <tcp_listen_port>1810</tcp_listen_port>
      <sctp_listen_port>1811</sctp_listen_port>
      <use_ipv6>0</use_ipv6>
      <watchdog_timeout>3</watchdog_timeout>
      <reconnect_interval>30</reconnect_interval>
      <reconnect_max>3</reconnect_max>
      <request_retransmission_interval>10</request_retransmission_interval>
      <max_request_retransmission_count>3</max_request_retransmission_count>
      <receive_buffer_size>2048</receive_buffer_size>
      <advertised_hostname>nas1.research1.org</advertised_hostname>
      <peer_table>
          <expiration_time>1</expiration_time>
          <peer>
              <hostname>server.research2.org</hostname>
              <port>1812</port>
              <use_sctp>0</use_sctp>
              <tls_enabled>0</tls_enabled>
          </peer>
      </peer_table>
      <route_table>
          <expire_time>0</expire_time>
          <route>
             <realm>research2.org</realm>
             <role>1</role> 
             <redirect_usage>0</redirect_usage>
             <application>
                <application_id>1</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>server.research2.org</server>
                    <metric>2</metric>
                </peer_entry>
             </application>
             <application>
                <application_id>3</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>server.research2.org</server>
                    <metric>2</metric>
                </peer_entry>
             </application>
          </route>
          <default_route>
             <realm>research2.org</realm>
             <role>0</role>
             <redirect_usage>0</redirect_usage>
             <application>
                <application_id>1</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>server.research2.org</server>
                    <metric>4</metric>
                </peer_entry>
                <peer_entry>
                    <server>server.research2.org</server>
                    <metric>5</metric>
                </peer_entry>
             </application>
          </default_route>
      </route_table>
   </transport_mngt>
   <session_mngt>
      <max_sessions>10000</max_sessions>
      <auth_sessions>
         <stateful>1</stateful>
         <session_timeout>30</session_timeout>
         <lifetime_timeout>360</lifetime_timeout>
         <grace_period_timeout>30</grace_period_timeout>
         <abort_retry_timeout>20</abort_retry_timeout>
      </auth_sessions>
      <acct_sessions>
         <session_timeout>30</session_timeout>
         <interim_interval>5</interim_interval>
         <realtime>1</realtime>
      </acct_sessions>
   </session_mngt>
   <log>
      <flags>
         <debug>enabled</debug>
         <trace>enabled</trace>
         <info>enabled</info>
      </flags>
      <target>
         <console>enabled</console>
         <syslog>disabled</syslog>
      </target>
   </log>
</configuration>

=== pol51/OpenDiameter/cplusplus/libdiameter/config/isp.local.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<configuration>
   <general>
      <product>Open Diameter</product>
      <version>1</version>
      <vendor_id>0</vendor_id>
      <supported_vendor_id>0</supported_vendor_id>
      <supported_vendor_id>1</supported_vendor_id>
      <auth_application_id>1</auth_application_id>
      <auth_application_id>2</auth_application_id>
      <auth_application_id>10000</auth_application_id>
      <acct_application_id>3</acct_application_id>
      <acct_application_id>4</acct_application_id>
      <acct_application_id>20000</acct_application_id>
      <vendor_specific_application_id>
          <vendor_id>31</vendor_id>
          <auth_application_id>1</auth_application_id>
          <acct_application_id>4</acct_application_id>
      </vendor_specific_application_id>
      <vendor_specific_application_id>
          <vendor_id>41</vendor_id>
          <auth_application_id>5</auth_application_id>
          <acct_application_id>6</acct_application_id>
      </vendor_specific_application_id>
   </general>
   <parser>
      <dictionary>config/dictionary.xml</dictionary>
   </parser>
   <transport_mngt>
      <identity>server.isp.net</identity>
      <realm>isp.net</realm>
      <tcp_listen_port>1812</tcp_listen_port>
      <sctp_listen_port>1813</sctp_listen_port>
      <use_ipv6>0</use_ipv6>
      <watchdog_timeout>4</watchdog_timeout>
      <reconnect_interval>30</reconnect_interval>
      <reconnect_max>3</reconnect_max>
      <request_retransmission_interval>10</request_retransmission_interval>
      <max_request_retransmission_count>3</max_request_retransmission_count>
      <advertised_hostname>server1.isp.net</advertised_hostname>
      <advertised_hostname>server2.isp.net</advertised_hostname>
      <peer_table>
          <expiration_time>1</expiration_time>
          <peer>
              <hostname>nas.access1.net</hostname>
              <port>1811</port>
              <use_sctp>1</use_sctp>
              <tls_enabled>0</tls_enabled>
          </peer>
          <peer>
              <hostname>nas.access2.net</hostname>
              <port>1811</port>
              <use_sctp>1</use_sctp>
              <tls_enabled>0</tls_enabled>
          </peer>
          <peer>
              <hostname>nas.access3.net</hostname>
              <port>1811</port>
              <use_sctp>1</use_sctp>
              <tls_enabled>0</tls_enabled>
          </peer>
      </peer_table>
      <route_table>
          <expire_time>0</expire_time>
          <route>
             <realm>access1.net</realm>
             <role>0</role> 
             <application>
                <application_id>0</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>nas.access2.net</server>
                    <metric>2</metric>
                </peer_entry>
             </application>
             <application>
                <application_id>1</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>nas.access1.net</server>
                    <metric>2</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas2.access1.net</server>
                    <metric>4</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas3.access1.net</server>
                    <metric>5</metric>
                </peer_entry>
             </application>
          </route>
          <route>
             <realm>access2.net</realm>
             <role>0</role> 
             <application>
                <application_id>1</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>nas.access2.net</server>
                    <metric>2</metric>
                </peer_entry>
             </application>
          </route>
          <route>
             <realm>access3.net</realm>
             <role>0</role> 
             <application>
                <application_id>0</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>nas.access3.net</server>
                    <metric>2</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas2.access3.net</server>
                    <metric>4</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas3.access3.net</server>
                    <metric>5</metric>
                </peer_entry>
             </application>
             <application>
                <application_id>1</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>nas.access3.net</server>
                    <metric>2</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas2.access3.net</server>
                    <metric>4</metric>
                </peer_entry>
                <peer_entry>
                    <server>nas3.access3.net</server>
                    <metric>5</metric>
                </peer_entry>
             </application>
          </route>
          <default_route>
             <realm>access1.net</realm>
             <role>0</role> 
             <application>
                <application_id>0</application_id>
                <vendor_id>0</vendor_id>
                <peer_entry>
                    <server>nas.access1.net</server>
                    <metric>4</metric>
                </peer_entry>
             </application>
          </default_route>
      </route_table>
   </transport_mngt>
   <session_mngt>
      <max_sessions>10000</max_sessions>
      <auth_sessions>
         <stateful>1</stateful>
         <session_timeout>30</session_timeout>
         <lifetime_timeout>360</lifetime_timeout>
         <grace_period_timeout>30</grace_period_timeout>
         <abort_retry_timeout>20</abort_retry_timeout>
      </auth_sessions>
      <acct_sessions>
         <session_timeout>30</session_timeout>
         <interim_interval>5</interim_interval>
         <realtime>1</realtime>
      </acct_sessions>
   </session_mngt>
   <log>
      <flags>
         <debug>enabled</debug>
         <trace>enabled</trace>
         <info>enabled</info>
      </flags>
      <target>
         <console>enabled</console>
         <syslog>enabled</syslog>
      </target>
   </log>
</configuration>
