=== pol51/OpenDiameter/cplusplus/applications/pana/config/config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

     <!ELEMENT pana_configuration (general, (client|auth_agent))>

     <!ELEMENT general (thread_count, listen_port, interface_name, ipv6,
                        protection_capability, dictionary_filename,
                        mobility, separate, abort_on_first_eap_failure,
                        eap_piggyback, retransmission_param, ppac_config,
                        keep_alive_interval, wpa_bootstrap)>
                        
     <!ELEMENT thread_count (#PCDATA)>
     <!ELEMENT listen_port (#PCDATA)>
     <!ELEMENT interface_name (#PCDATA)>
     <!ELEMENT ipv6 (#PCDATA)>
     <!ELEMENT protection_capability (#PCDATA)>
     <!ELEMENT dictionary_filename (#PCDATA)>
     <!ELEMENT mobility (#PCDATA)>
     <!ELEMENT separate (#PCDATA)>
     <!ELEMENT abort_on_first_eap_failure (#PCDATA)>
     <!ELEMENT eap_piggyback (#PCDATA)>
     
     <!ELEMENT retransmission_param (initial_rt_timeout, max_rt_count,
                                     max_rt_timeout, max_rt_duration)>
     <!ELEMENT ppac_config (dhcpv4, dhcpv6, autoconfv6, dhcpv4_ipsec, ikev2)>

     <!ELEMENT keep_alive_interval (#PCDATA)>
     <!ELEMENT wpa_bootstrap (#PCDATA)>

     <!ELEMENT initial_rt_timeout (#PCDATA)>
     <!ELEMENT max_rt_count (#PCDATA)>
     <!ELEMENT max_rt_timeout (#PCDATA)>
     <!ELEMENT max_rt_duration (#PCDATA)>

     <!ELEMENT dhcpv4 (#PCDATA)>
     <!ELEMENT dhcpv6 (#PCDATA)>
     <!ELEMENT autoconfv6 (#PCDATA)>
     <!ELEMENT dhcpv4_ipsec (#PCDATA)>
     <!ELEMENT ikev2 (#PCDATA)>

     <!ELEMENT client (paa_ip_address?, paa_port_number?,
                       paa_mcast_address, isp_info?)>
                       
     <!ELEMENT paa_ip_address (#PCDATA)>
     <!ELEMENT paa_port_number (#PCDATA)>
     <!ELEMENT paa_mcast_address (#PCDATA)>
     <!ELEMENT isp_info (id, name)>

     <!ELEMENT id (#PCDATA)>
     <!ELEMENT name (#PCDATA)>

     <!ELEMENT auth_agent (mcast_address, session_lifetime,
                           grace_period, use_cookie, nap_info?,
                           isp_info*, ep_id*, carry_device_id)>
                           
     <!ELEMENT mcast_address (#PCDATA)>
     <!ELEMENT session_lifetime (#PCDATA)>
     <!ELEMENT grace_period (#PCDATA)>
     <!ELEMENT use_cookie (#PCDATA)>
     <!ELEMENT nap_info (id, name)>
     <!ELEMENT ep_id (type, id)>
     <!ELEMENT carry_device_id (#PCDATA)>
     
     <!ELEMENT type (#PCDATA)>

=== pol51/OpenDiameter/cplusplus/libpana/config/paa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pana_configuration SYSTEM "config.dtd">
<pana_configuration>

    <general>

        <!-- Controls the number of threads in the pool
             to be spawned at startup -->
        <thread_count>5</thread_count>
    
        <!-- UDP port that the PAA will listen to
             for Pac messages -->
        <listen_port>3001</listen_port>
    
        <!-- Name of interface to use for PANA
             messages -->
        <interface_name>eth1</interface_name>
    
        <!-- Flag to indicate that this library
             will try to use IPv6 stack 
              0 - use only IPv4
              1 - attempt to use IPv6 --> 
        <ipv6>1</ipv6>
    
        <!-- Protection capability advertised by
             the PAA, valid values are:
            -1 - Dont use
             0 - L2_PROTECTION
             1 - IPSEC_PROTECTION -->
        <protection_capability>1</protection_capability>
    
        <!-- Filename of the parser dictionary -->
        <dictionary_filename>config/dictionary.xml</dictionary_filename>

        <!-- Session resumption flag -->
        <mobility>0</mobility>

        <!-- Controls wether S-flag will be set (i.e. the PAA
             advertise supports separate NAP/ISP authentication).
             This is a required configuration entry and MUST be 
             provide to enable/disable S-flag -->
        <separate>0</separate> 

        <!-- Abort on 1st eap failure -->
        <abort_on_first_eap_failure>0</abort_on_first_eap_failure>

        <!-- Controls wether EAP payload will be sent
             in the PSR/PSA message during stateful
             discovery. Note that this is only
             valid if use_cookie is 0. Also, if this
             is set and used, then the separate flag
             will be ingnored -->
        <eap_piggyback>0</eap_piggyback> 

        <!-- Post pana address configuration options -->
        <ppac_config>
           <!-- suppots dhcpv4 -->
	   <dhcpv4>1</dhcpv4> 

           <!-- suppots dhcpv6 -->
	   <dhcpv6>0</dhcpv6> 

           <!-- supports IPv6 stateless autoconfig -->
           <autoconfv6>1</autoconfv6>

           <!-- supports DHCPv4 via IPsec tunnel -->
           <dhcpv4_ipsec>0</dhcpv4_ipsec>

           <!-- supports IKEv2 -->
           <ikev2>0</ikev2>

        </ppac_config>

        <!-- Configurable retransmission parameters
	     as specified in the PANA draft. See
	     Sec 10 of the draft for rules govering
	     message retranmission -->
        <retransmission_param>
            <!-- Initial retransmission timeout -->
            <initial_rt_timeout>10</initial_rt_timeout>

            <!-- Maximum retransmission count -->
            <max_rt_count>3</max_rt_count>

            <!-- Maximum retransmission timeout -->
            <max_rt_timeout>120</max_rt_timeout>

            <!-- Maximum retransmission duration -->
            <max_rt_duration>120</max_rt_duration>
        </retransmission_param>

        <!-- Re-Auth timer (interval) -->
        <keep_alive_interval>10</keep_alive_interval>

        <!-- WPA (802.11i) bootstrap support 
             A 256-bit PMK key will be generated during the
             Authorize method (and passed to authorization
             script) when this option is enabled. 
             -->
        <wpa_bootstrap>1</wpa_bootstrap>
    </general>

    <auth_agent>

        <!-- Pre-configure mcast address the PAA will 
	     listen too, note that default value
	     is set in the schema definition -->
        <mcast_address>ff01::15</mcast_address>

        <!-- Session lifetime enforced by this PAA -->
        <session_lifetime>360</session_lifetime>

        <!-- Grace period is the additional time 
             given to the Pac to allow for re-authorization.
             Session lifetime + grace period is what
             is sent to the Pac during binding --> 
        <grace_period>30</grace_period>

        <!-- Controls wether the PAA will use stateful or
             stateless discovery. A value of 1 will allow
             for a cookie based stateless discovery -->
        <use_cookie>1</use_cookie> 

        <!-- NAP provider information to be sent on
             Start request. Note that if name is empty,
             the NAP-Information will not be sent -->
        <nap_info>
           <id>1</id>
           <name>Provider1.com</name>
        </nap_info>

        <!-- List of ISP provider information. All 
             entries will be sent in the ISP-Information
             AVP except those with empty names -->
        <isp_info>
           <id>2</id>
           <name>Provider2.com</name>
        </isp_info>

        <isp_info>
           <id>3</id>
           <name>Provider3.com</name>
        </isp_info>

        <!-- List of local and remote EP device Id's 
             supported by this PAA -->
        <ep_id>
           <!-- Valid values for type are:
              0 - UNKNOWN
              1 - IPV4_ADDRESS
              2 - IPV6_ADDRESS
              6 - 802_MAC_ADDRESS
              x - see IANA address family assignment -->
           <type>6</type>
           <id>00080DF6E961</id>
        </ep_id>
        <ep_id>
           <type>6</type>
           <id>00080DF6E962</id>
        </ep_id>
        <ep_id>
           <type>6</type>
           <id>00080DF6E963</id>
        </ep_id>

        <!-- Controls wether the device-id of the PAA
             will be sent to the PaC during bind or
             first auth request -->
        <carry_device_id>1</carry_device_id> 
        
    </auth_agent>
    
</pana_configuration>

=== pol51/OpenDiameter/cplusplus/libpana/config/pac.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pana_configuration SYSTEM "config.dtd">
<pana_configuration>

    <general>

        <!-- UDP port that the PaC will listen to
             for PAA messages. Note that this
             does not bind to any address or interface
             so it will receive Pac messages on any
             interface -->
        <listen_port>3002</listen_port>

        <!-- Filename of the parser dictionary -->
        <dictionary_filename>config/dictionary.xml</dictionary_filename>

        <!-- Configurable retransmission parameters
             as specified in the PANA draft. See
             Sec 10 of the draft for rules govering
             message retranmission -->
        <retransmission_param>
           <!-- Initial retransmission timeout -->
           <initial_rt_timeout>10</initial_rt_timeout>

           <!-- Maximum retransmission count -->
           <max_rt_count>3</max_rt_count>

           <!-- Maximum retransmission timeout -->
           <max_rt_timeout>5</max_rt_timeout>

           <!-- Maximum retransmission duration -->
           <max_rt_duration>360</max_rt_duration>
        </retransmission_param>

        <!-- WPA (802.11i) bootstrap support
             A 256-bit PMK key will be generated during the
             Authorize method (and passed to authorization
             script) when this option is enabled.
          -->
        <wpa_bootstrap>1</wpa_bootstrap>

        <!-- Session lifetime enforces when this PANA
             session will end. Note that this can controls
             the deletion of the PANA session whether
             the session was auth successfully or not -->
        <session_lifetime>360</session_lifetime>

    </general>

    <client>

        <!-- Pre-configure IP address or hostname of the PAA.
             Note that the library automatically detects whether
             your are going to use IPv6 or IPv4 based on
             this address -->
        <paa_ip_address>localhost</paa_ip_address>

        <!-- PAA port number used in conjuction with paa_ip_address -->
        <paa_port_number>3001</paa_port_number>

        <!-- eap response timeout. Number of seconds the EAP layer
             is allowed to send an EAP response before an EAP_RESP_TIMEOUT
             event occurs -->
        <eap_response_timeout>3</eap_response_timeout>

        <!-- Controls wether EAP payload will be sent
             in the PANA-Auth-Answer message during auth phase --> 
        <eap_piggyback>0</eap_piggyback>

    </client>

</pana_configuration>
