=== pol51/OpenDiameter/cplusplus/applications/pana/config/dictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>
     <!--
        $Log: dictionary.dtd,v $
        Revision 1.5  2004/08/25 09:51:47  canelaman
        Makefile.am

        Revision 1.2  2004/04/08 15:35:06  vfajardo
        Fixes to protocol id parsring

        Revision 1.1  2003/10/25 23:13:17  vfajardo
        Adding PANA to open diameter

        Revision 1.1  2003/10/10 18:17:52  victorf
        moved from src

        Revision 1.2  2003/10/10 18:16:08  victorf
        updated

        Revision 1.1  2003/09/22 20:10:16  victorf
        Migration to .NET 2003

     -->
     <!ELEMENT dictionary (vendor*, base, application*)>
     <!ATTLIST dictionary 
          protocol CDATA #REQUIRED
     >

     <!ELEMENT vendor EMPTY>
     <!ATTLIST vendor
          id CDATA #REQUIRED
          name CDATA #REQUIRED
     >

     <!ELEMENT base (command*, typedefn+, avp+)>
     <!ATTLIST base
          uri CDATA #IMPLIED
     >

     <!ELEMENT application (command*, typedefn*, avp*)>
     <!ATTLIST application
          id CDATA #REQUIRED
          name CDATA #IMPLIED
          uri CDATA #IMPLIED
     >
     <!-- Modified by Ohba 
     <!ELEMENT command (requestrules*, answerrules*)>
     <!ATTLIST command
          name CDATA #REQUIRED
          code CDATA #REQUIRED
          vendor-id CDATA #IMPLIED
     >
     -->
     <!ELEMENT command (requestrules*, answerrules*)>
     <!ATTLIST command
          name CDATA #REQUIRED
          code CDATA #REQUIRED
          application-id CDATA #IMPLIED
          pbit CDATA #IMPLIED
     >

     <!ELEMENT typedefn EMPTY>
     <!ATTLIST typedefn
          type-name ID #REQUIRED
          type-parent IDREF #IMPLIED
          description CDATA #IMPLIED
     >
     <!ELEMENT avp ((type | grouped), (enum*))>
     <!ATTLIST avp
          name ID #REQUIRED
          description CDATA #IMPLIED
          code CDATA #REQUIRED
          may-encrypt (yes | no) "yes"
          mandatory (must | may | mustnot | shouldnot) "may"
          protected (must | may | mustnot | shouldnot) "may"
          vendor-id CDATA #IMPLIED
     >
     <!ELEMENT type EMPTY>
     <!ATTLIST type
          type-name IDREF #REQUIRED
     >
     <!-- Modified by Ohba
     <!ELEMENT grouped (gavp+)>
     -->
     <!ELEMENT grouped (fixed*, required*, optional*, fixed*)>
     <!-- Deleted by Ohba 
     <!ELEMENT gavp EMPTY>
     <!ATTLIST gavp
          name IDREF #REQUIRED
          vendor-id CDATA #IMPLIED
     >
     -->
     <!ELEMENT enum EMPTY>
     <!ATTLIST enum
          name CDATA #REQUIRED
          code CDATA #REQUIRED
     >

     <!-- <!ELEMENT requestrules (avprule+)> Modified by Ohba -->
     <!ELEMENT requestrules (fixed*, required*, optional*, fixed*)>

     <!-- <!ELEMENT answerrules (avprule+)> Modified by Ohba -->
     <!ELEMENT answerrules (fixed*, required*, optional*, fixed*)>

     <!-- Next 3 lines were added by ohba -->
     <!ELEMENT fixed (avprule+)>
     <!ELEMENT required (avprule+)>
     <!ELEMENT optional (avprule+)>

     <!-- Modified by Ohba 
     <!ELEMENT avprule EMPTY>
     <!ATTLIST avprule
          name IDREF #REQUIRED
             position (first | last | unspecified)  "unspecified"
             maximum CDATA "none"
             minimum CDATA "0"
     >
     -->
     <!ELEMENT avprule EMPTY>
     <!ATTLIST avprule
          name IDREF #REQUIRED
             maximum CDATA "none"
             minimum CDATA "0"
     >

=== pol51/OpenDiameter/cplusplus/applications/pana/config/pana_dictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<dictionary>
    <!-- *********************** Message types *************************** -->
    <command name="PANA-Client-Initiation" code="1">
      <answerrules>
      </answerrules>
    </command>
    <command name="PANA-Auth" code="2">
      <requestrules>
        <optional>
           <avprule name="EAP-Payload" maximum="1" minimum="0" />
           <avprule name="Algorithm" maximum="1" minimum="0" />
           <avprule name="Nonce" maximum="1" minimum="0" />
           <avprule name="Result-Code" maximum="1" minimum="0" />
           <avprule name="Session-Lifetime" maximum="1" minimum="0" />
           <avprule name="Key-Id" maximum="1" minimum="0" />
           <avprule name="AUTH" maximum="1" minimum="0" />
        </optional>
      </requestrules>
      <answerrules>
        <optional>
           <avprule name="Nonce" maximum="1" minimum="0" />
           <avprule name="EAP-Payload" maximum="1" minimum="0" />
           <avprule name="Key-Id" maximum="1" minimum="0" />
           <avprule name="AUTH" maximum="1" minimum="0" />
        </optional>
      </answerrules>
    </command>
    <command name="PANA-Termination" code="3">
      <requestrules>
        <fixed>
           <avprule name="Termination-Cause" maximum="1" minimum="1" />
        </fixed>
        <optional>
           <avprule name="AUTH" maximum="1" minimum="0" />
        </optional>
      </requestrules>
      <answerrules>
        <optional>
           <avprule name="AUTH" maximum="1" minimum="0" />
        </optional>
      </answerrules>
    </command>
    <command name="PANA-Notification" code="4">
      <requestrules>
        <optional>
           <avprule name="Result-Code" maximum="1" minimum="0" />
           <avprule name="AUTH" maximum="1" minimum="0" />
        </optional>
      </requestrules>
      <answerrules>
        <optional>
           <avprule name="AUTH" maximum="1" minimum="0" />
        </optional>
      </answerrules>
    </command>
    <!-- ********************** End Message types ************************ -->

    <!-- ************************ typedefn's ************************ -->
    <typedefn type-name="Any"/> <!-- Added by Ohba-->
    <typedefn type-name="OctetString"/>
    <typedefn type-name="UTF8String" type-parent="OctetString"/>
    <typedefn type-name="Address" type-parent="OctetString"/>
    <typedefn type-name="Integer32"/>
    <typedefn type-name="Integer64"/>
    <typedefn type-name="Unsigned32"/>
    <typedefn type-name="Time" type-parent="Unsigned32"/>
    <typedefn type-name="Unsigned64"/>
    <!-- *********************** End Typedefns ********************** -->

    <!-- ***************** PANA PROTOCOL AVPS ************** -->
    <avp name="AVP" code="0"> <!-- Added by Ohba -->
      <type type-name="Any"/>
    </avp>
    <avp name="Algorithm" code="1" mandatory="must">
      <type type-name="Unsigned32"/>
    </avp>
    <avp name="AUTH" code="2" mandatory="must">
      <type type-name="OctetString"/>
    </avp>
    <avp name="EAP-Payload" code="3" mandatory="must">
      <type type-name="OctetString"/>
    </avp>
    <avp name="Key-Id" code="4" mandatory="must">
      <type type-name="Integer32"/>
    </avp>
    <avp name="Nonce" code="5" mandatory="must">
      <type type-name="OctetString"/>
    </avp>
    <avp name="Result-Code" code="6" mandatory="must">
      <type type-name="Unsigned32"/>
    </avp>
    <avp name="Session-Lifetime" code="7" mandatory="must">
      <type type-name="Unsigned32"/>
    </avp>
    <avp name="Termination-Cause" code="8" mandatory="must">
      <type type-name="Unsigned32"/>
      <enum name="Logout" code="1"/>
      <enum name="Administrative" code="4"/>
      <enum name="Session Timeout" code="8"/>
    </avp>
</dictionary>
