=== pol51/OpenDiameter/cplusplus/applications/pana/config/pana_config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

     <!ELEMENT pana_configuration (general, (client|agent))>

     <!ELEMENT general (listen_port, dictionary_filename, 
                        eap_piggyback, retransmission_param,
                        keep_alive_interval, wpa_bootstrap)>

     <!ELEMENT listen_port (#PCDATA)>
     <!ELEMENT dictionary_filename (#PCDATA)>
     <!ELEMENT eap_piggyback (#PCDATA)>
     <!ELEMENT session_lifetime (#PCDATA)>

     <!ELEMENT retransmission_param (initial_rt_timeout, max_rt_count,
                                     max_rt_timeout, max_rt_duration)>

     <!ELEMENT keep_alive_interval (#PCDATA)>
     <!ELEMENT wpa_bootstrap (#PCDATA)>

     <!ELEMENT initial_rt_timeout (#PCDATA)>
     <!ELEMENT max_rt_count (#PCDATA)>
     <!ELEMENT max_rt_timeout (#PCDATA)>
     <!ELEMENT max_rt_duration (#PCDATA)>

     <!ELEMENT client (paa_ip_address, paa_port_number)>

     <!ELEMENT paa_ip_address (#PCDATA)>
     <!ELEMENT paa_port_number (#PCDATA)>

     <!ELEMENT agent (optimized_handshake, carry_lifetime, retry_psr)>

     <!ELEMENT optimized_handshake (#PCDATA)>
     <!ELEMENT carry_lifetime (#PCDATA)>
     <!ELEMENT retry_psr (#PCDATA)>

=== pol51/OpenDiameter/cplusplus/applications/pana/config/pana_pac.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pana_configuration SYSTEM "pana_config.dtd">
<pana_configuration>

    <general>

        <!-- UDP port that the PaC will listen to
             for PAA messages. Note that this
             does not bind to any address or interface
             so it will receive Pac messages on any
             interface -->
        <listen_port>3001</listen_port>

        <!-- Filename of the parser dictionary -->
        <dictionary_filename>config/dictionary.xml</dictionary_filename>

        <!-- Session resumption flag -->
        <mobility>0</mobility>

        <!-- Controls wether EAP payload will be sent
             in the PSR/PSA message during stateful
             discovery. Note that this is only
             valid if use_cookie is 0. Also, if this
             is set and used, then the separate flag
             will be ingnored -->
        <eap_piggyback>0</eap_piggyback>

        <!-- Configurable retransmission parameters
             as specified in the PANA draft. See
             Sec 10 of the draft for rules govering
             message retranmission -->
        <retransmission_param>
           <!-- Initial retransmission timeout -->
           <initial_rt_timeout>10</initial_rt_timeout>

           <!-- Maximum retransmission count -->
           <max_rt_count>3</max_rt_count>

           <!-- Maximum retransmission timeout -->
           <max_rt_timeout>120</max_rt_timeout>

           <!-- Maximum retransmission duration -->
           <max_rt_duration>10</max_rt_duration>
        </retransmission_param>

        <!-- Re-Auth timer (interval) -->
        <keep_alive_interval>10</keep_alive_interval>

        <!-- WPA (802.11i) bootstrap support
             A 256-bit PMK key will be generated during the
             Authorize method (and passed to authorization
             script) when this option is enabled.
          -->
        <wpa_bootstrap>1</wpa_bootstrap>

        <!-- Session lifetime enforces when this PANA
             session will end. Note that this can controls
             the deletion of the PANA session whether
             the session was auth successfully or not -->
        <session_lifetime>360</session_lifetime>

    </general>

    <client>

        <!-- Pre-configure IP address or hostname of the PAA.
             Note that the library automatically detects whether
             your are going to use IPv6 or IPv4 based on
             this address -->
        <paa_ip_address></paa_ip_address>

        <!-- PAA port number used in conjuction with paa_ip_address -->
        <paa_port_number>3001</paa_port_number>

    </client>

</pana_configuration>
