=== pol51/OpenDiameter/cplusplus/libpana/config/users.dtd
<?xml version="1.0" encoding="UTF-8" ?>

     <!ELEMENT user_dbase (user+)>
     <!ELEMENT user (name, pass, auth)>
     
     <!ELEMENT name (#PCDATA)>
     <!ELEMENT pass (#PCDATA)>
     <!ELEMENT auth (#PCDATA)>

=== pol51/OpenDiameter/cplusplus/libpana/config/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE user_dbase SYSTEM "users.dtd">
<user_dbase>
   <user>
      <name>user1</name>
      <pass>12345</pass>
      <auth>md5</auth>
   </user>
   <user>
      <name>user1@isp.net</name>
      <pass>12345</pass>
      <auth>archie</auth>
   </user>
   <user>
      <name>local_nas@opendiameter.org</name>
      <pass>12345</pass>
      <auth>archie</auth>
   </user>
   <user>
      <name>user3</name>
      <pass>12345</pass>
      <auth>md5</auth>
   </user>
   <user>
      <name>user4</name>
      <pass>12345</pass>
      <auth>archie</auth>
   </user>
   <user>
      <name>user5</name>
      <pass>12345</pass>
      <auth>md5</auth>
   </user>
</user_dbase>
