=== pol51/OpenDiameter/cplusplus/applications/aaa/config/aaad_user_db.dtd
<?xml version="1.0" encoding="UTF-8" ?>

     <!ELEMENT user_db (user_entry*, default_entry)>

     <!ELEMENT user_entry (name_match, eap_method, archie?, md5?)>
     <!ELEMENT default_entry (eap_method, archie?, md5?)>

     <!ELEMENT name_match (#PCDATA)>
     <!ELEMENT eap_method (#PCDATA)>

     <!ELEMENT archie (shared_secret_file)>

     <!ELEMENT shared_secret_file (#PCDATA)>

     <!ELEMENT md5 (password_type, secret)>

     <!ELEMENT password_type (#PCDATA)>
     <!ELEMENT secret (#PCDATA)>

=== pol51/OpenDiameter/cplusplus/applications/aaa/config/aaad_user_db.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE user_db SYSTEM "aaad_user_db.dtd">
<user_db>

    <!-- 
              !!! NOTES !!!

         The aaad uses this user database
         file to determine the eap method
         to be used per user or per group
         of users.

         The Format is very simple. Each
         entry has a <name_match> string
         that aaad uses to see match against
         the username of each authentication
         attempt. The match does not have
         to be exact. Currently, it uses
         substring searches to find a match.
         So as an example, if an incomming
         identity is:

            user@domain.net

         An <name_match> value of "us" or
         "user" or "domain" will match this
         identity. Future version may use
         different matching algorithm. For
         now we use the simpliest form. In
         addtion, there is a <default_entry>
         which is used if no match can be
         made.

         Once a match is made, the specified
         eap method is used to authenticate
         the user. For archie methods, the
         entry can point to a binary shared
         secret file. Note that additional
         methods will be added in the future
         that will expand this configuration
         file.

      -->
    <user_entry>
	<name_match>testuser@localdomain.net</name_match>
	<eap_method>fast</eap_method>
	<fast>
	   <shared_secret_file>aaad.dtd</shared_secret_file>
	   <inner_eap_method>md5</inner_eap_method>
 	</fast>
	<md5>
	   <password_type>flat</password_type>
          <secret>abcd1234</secret>
	</md5>
     </user_entry>
   

    <default_entry>
       <eap_method>fast</eap_method>
    </default_entry>

</user_db>
